#!/bin/bash

for i in *.txt; do
  words=$(wc -w "${i}" | cut -d' ' -f1)
  readarray -t errors < <(aspell --lang=zz list --dont-suggest <"${i}" | sort -u)
  percentage=$(((6 - ${#errors[@]} * 100 / words)))
  printf "\n====\n%s %s/%s - %s\n" "${i}" "${words}" "${#errors[@]}" "${percentage}"
  printf "%s\n" "${errors[@]}"
done >spellreview
